### ISSUE TITLE
The saveCallback of CropView.startCrop(...) is very very slow！！！

### ISSUE THREAD

**Issue by TroyRay** [IsseiAoki/SimpleCropView#65]
When I load a picture which the size is more than 3M,I will take a lot of time to get the onSaveCallback of the cropview!!!

**Comment by androidapkr** [comment]
Two issue: 
Issue 1 : When i used camera image for crop, it will take long time to crop image. 

Issue 2: For that i used ProgressBar to show progress while image cropping but its had another issue that CropView is reseted the bounds that i selected and get default cropped image instead of the selected position from view.

**Comment by IsseiAoki** [comment]
Sorry for late response.
I think it is not a bug. It is related to the extension of the image file.
As default, this library uses PNG extension for the cropped image file.
PNG image saving process is little slower than JPEG (because JPEG image saving process uses hardware acceleration).
I use PNG file for preventing the loss of the image quality.

@androidapkr I'm investigating this issue, but I cannot replicate the phenomenon.
If possible, please send me a minimal sample project that replicates the phenomenon.

**Comment by vikey89** [comment]
+1
